import { GeneratedAssetBundle } from './types';
import jsPDF from 'jspdf';

/**
 * Format entire asset bundle into structured Markdown string
 */
export function formatBundleToMarkdown(bundle: GeneratedAssetBundle): string {
  const dateStr = bundle.createdAt
    ? new Date(bundle.createdAt).toLocaleDateString()
    : new Date().toLocaleDateString();

  return `# ${bundle.title}
*Generated by RepurposeAI on ${dateStr}*
${bundle.sourceUrl ? `*Source: ${bundle.sourceUrl}*\n` : ''}
---

## 📌 Executive Summary
${bundle.summary}

---

## 💼 LinkedIn Post
**Hook:**
> ${bundle.linkedinPost.hook}

**Post Body:**
${bundle.linkedinPost.body}

**Key Bullets:**
${bundle.linkedinPost.bulletPoints.map((b) => `- ${b}`).join('\n')}

**Call to Action:**
${bundle.linkedinPost.callToAction}

**Hashtags:**
${bundle.linkedinPost.hashtags.join(' ')}

---

## 🐦 Twitter / X Thread (${bundle.twitterThread.length} Tweets)
${bundle.twitterThread
  .map(
    (t) => `### Tweet ${t.tweetNumber} / ${bundle.twitterThread.length}
${t.content}`
  )
  .join('\n\n')}

---

## 🎬 Short-Form Video Scripts (Reels / TikTok / Shorts)
${bundle.videoScripts
  .map(
    (v, i) => `### Video Concept #${i + 1} (${v.targetDuration})
- **Hook:** "${v.hook}"
- **Visual Direction:** ${v.visualDirection}
- **Voiceover Script:**
${v.voiceoverScript}
- **Call to Action:** "${v.callToAction}"`
  )
  .join('\n\n')}

---

## 🔍 SEO Meta Package
- **Meta Title:** ${bundle.seoMeta.metaTitle}
- **Meta Description:** ${bundle.seoMeta.metaDescription}
- **Suggested Slug:** \`/${bundle.seoMeta.slugSuggestion}\`
- **Keywords:** ${bundle.seoMeta.keywords.join(', ')}

---

## 📧 Newsletter & Executive Brief
**TL;DR:**
${bundle.newsletterBrief.tldr}

**Key Takeaways:**
${bundle.newsletterBrief.keyTakeaways.map((t) => `- ${t}`).join('\n')}

**Highlight Quote:**
> ${bundle.newsletterBrief.highlightQuote}
`;
}

/**
 * Download text or JSON as a file in the browser
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Export bundle as a Markdown (.md) file
 */
export function exportBundleAsMarkdown(bundle: GeneratedAssetBundle): void {
  const markdown = formatBundleToMarkdown(bundle);
  const slug = bundle.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .slice(0, 30);
  downloadFile(markdown, `repurpose-${slug}.md`, 'text/markdown;charset=utf-8');
}

/**
 * Export bundle as a JSON (.json) file
 */
export function exportBundleAsJSON(bundle: GeneratedAssetBundle): void {
  const jsonStr = JSON.stringify(bundle, null, 2);
  const slug = bundle.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .slice(0, 30);
  downloadFile(jsonStr, `repurpose-${slug}.json`, 'application/json;charset=utf-8');
}

/**
 * Export bundle as a styled PDF document using jsPDF
 */
export function exportBundleAsPDF(bundle: GeneratedAssetBundle): void {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'pt',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const maxWidth = pageWidth - margin * 2;
  let cursorY = margin;

  const checkPageBreak = (neededHeight: number) => {
    if (cursorY + neededHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      cursorY = margin;
    }
  };

  // Header Banner
  doc.setFillColor(15, 23, 42); // Dark slate
  doc.rect(0, 0, pageWidth, 70, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('RepurposeAI — Distribution Bundle', margin, 42);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, margin, 58);

  cursorY = 95;

  // Title
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  const titleLines = doc.splitTextToSize(bundle.title, maxWidth);
  doc.text(titleLines, margin, cursorY);
  cursorY += titleLines.length * 20 + 10;

  // Summary
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(10);
  doc.setTextColor(71, 85, 105);
  const summaryLines = doc.splitTextToSize(bundle.summary, maxWidth);
  doc.text(summaryLines, margin, cursorY);
  cursorY += summaryLines.length * 14 + 20;

  const renderSection = (heading: string, contentLines: string[]) => {
    checkPageBreak(40 + contentLines.length * 14);

    doc.setFillColor(241, 245, 249);
    doc.roundedRect(margin, cursorY - 12, maxWidth, 24, 4, 4, 'F');

    doc.setTextColor(99, 102, 241); // Indigo
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text(heading, margin + 8, cursorY + 4);
    cursorY += 28;

    doc.setTextColor(30, 41, 59);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9.5);

    contentLines.forEach((line) => {
      const wrapped = doc.splitTextToSize(line, maxWidth - 16);
      checkPageBreak(wrapped.length * 13);
      doc.text(wrapped, margin + 8, cursorY);
      cursorY += wrapped.length * 13 + 4;
    });

    cursorY += 15;
  };

  // 1. LinkedIn
  renderSection('💼 LinkedIn Post', [
    `HOOK: ${bundle.linkedinPost.hook}`,
    '',
    bundle.linkedinPost.body,
    '',
    'KEY POINTS:',
    ...bundle.linkedinPost.bulletPoints.map((b) => `• ${b}`),
    '',
    `CTA: ${bundle.linkedinPost.callToAction}`,
    `HASHTAGS: ${bundle.linkedinPost.hashtags.join(' ')}`,
  ]);

  // 2. Twitter Thread
  renderSection(
    `🐦 Twitter/X Thread (${bundle.twitterThread.length} Tweets)`,
    bundle.twitterThread.map(
      (t) => `[Tweet ${t.tweetNumber}/${bundle.twitterThread.length}]\n${t.content}\n`
    )
  );

  // 3. Video Scripts
  renderSection(
    '🎬 Short-Form Video Scripts (Reels / TikTok)',
    bundle.videoScripts.flatMap((v, idx) => [
      `--- Concept #${idx + 1} (${v.targetDuration}) ---`,
      `Hook: "${v.hook}"`,
      `Visuals: ${v.visualDirection}`,
      `Voiceover: ${v.voiceoverScript}`,
      `CTA: "${v.callToAction}"`,
      '',
    ])
  );

  // 4. SEO & Meta
  renderSection('🔍 SEO Meta Pack', [
    `Title: ${bundle.seoMeta.metaTitle}`,
    `Description: ${bundle.seoMeta.metaDescription}`,
    `Suggested Slug: /${bundle.seoMeta.slugSuggestion}`,
    `Keywords: ${bundle.seoMeta.keywords.join(', ')}`,
  ]);

  // 5. Newsletter
  renderSection('📧 Newsletter Executive Brief', [
    `TL;DR: ${bundle.newsletterBrief.tldr}`,
    '',
    'Key Takeaways:',
    ...bundle.newsletterBrief.keyTakeaways.map((k) => `• ${k}`),
    '',
    `Quote: "${bundle.newsletterBrief.highlightQuote}"`,
  ]);

  const slug = bundle.title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .slice(0, 30);
  doc.save(`repurpose-${slug}.pdf`);
}

/**
 * 1-Click copy to clipboard helper
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (err) {
    console.warn('Clipboard write failed, fallbacking:', err);
    try {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
      return true;
    } catch {
      return false;
    }
  }
}
